version: '3.8'

services:
  # Serviço da API
  api:
    build: .
    container_name: financial_api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Garante que o serviço de redis inicie antes da api
    depends_on:
      - redis

  # Serviço do Redis
  redis:
    image: redis:7-alpine
    container_name: financial_api_redis
    ports:
      - "6379:6379"